name = "jb-poss-app"
compatibility_date = "2024-09-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "jb_poss_db"
database_id = "70fbc72d-fab7-4691-8efa-ea652907aa97"
migrations_dir = "cloudflare"

[vars]
JWT_SECRET = "jb-super-secret-jwt-key-2026-secure-pos"
